config/routes.rb
BridgeProject::Application.routes.draw do
  devise_for :users

  root :to => "home#index"

  resources :services do
    member do
      put 'subscribe'
    end
  end

  match "search" => "services#search", :as => :search

end

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :service_service_types

  has_many :service_types, :through => :service_service_types

  has_many :service_followers
  has_many :followers, :through => :service_followers, :source => :user

  has_many :service_managers
  has_many :managers, :through => :service_managers, :source => :user

  searchable do
    text :site_name, :default_boost => 3
    text :service_types do
      service_types.map {|t| t.title }
    end
    text :state
    text :address
    text :zip
    text :transportation
    text :description
    text :restrictions
    text :website
  end
  after_save :reindex

  geocoded_by :steet_address
  after_validation :geocode,
    :if => lambda { |obj| obj.address_changed? || obj.city_changed? || obj.state_changed? || obj. zip_changed? }

  # Possibly will be slow inline... probably need to set some more specifics grained settings
  # http://outoftime.github.com/sunspot/docs/
  # or set this to be in a resque job
  def reindex
    Sunspot.index!
    # puts 'reindexed'
  end

  GEOCODE_URL = "http://maps.googleapis.com/maps/api/geocode/json"
  def geocode_address
    params = {
      :address => street_address,
      :sensor => false
    }
    geocode_response = RestClient.get(GEOCODE_URL, :params => params,
                                      :accept => :json)
  end

  def street_address
    [address, city, state, zip].join(" ")
  end
end


# == Schema Information
#
# Table name: services
#
#  id             :integer         not null, primary key
#  site_name      :string(255)
#  address        :string(255)
#  city           :string(255)
#  state          :string(255)
#  zip            :string(255)
#  phone          :string(255)
#  hours          :string(255)
#  transportation :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#  website        :string(255)
#  restrictions   :string(255)
#  latitude       :decimal(, )
#  longitude      :decimal(, )
#  description    :text
#  active         :boolean         default(FALSE)
#  void           :boolean         default(FALSE)
#  internal_notes :text
#

app/models/service_type.rb
#TODO: Everything
class ServiceType < ActiveRecord::Base
  has_many :service_service_types
  has_many :services, :through => :service_service_types
end

# == Schema Information
#
# Table name: service_types
#
#  id                      :integer         not null, primary key
#  title                   :string(255)
#  service_service_type_id :integer
#  created_at              :datetime
#  updated_at              :datetime
#

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # GET /services
  # GET /services.xml
  def index
    @services = Service.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @services }
    end
  end

  # GET /services/1
  # GET /services/1.xml
  def show
    @service = Service.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @service }
    end
  end

  # GET /services/new
  # GET /services/new.xml
  def new
    @service = Service.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @service }
    end
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
  end

  # POST /services
  # POST /services.xml
  def create
    @service = Service.new(params[:service])

    respond_to do |format|
      if @service.save
        format.html { redirect_to(@service, :notice => 'Service was successfully created.') }
        format.xml  { render :xml => @service, :status => :created, :location => @service }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @service.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /services/1
  # PUT /services/1.xml
  def update
    @service = Service.find(params[:id])

    respond_to do |format|
      if @service.update_attributes(params[:service])
        format.html { redirect_to(@service, :notice => 'Service was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @service.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.xml
  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    respond_to do |format|
      format.html { redirect_to(services_url) }
      format.xml  { head :ok }
    end
  end

  def search
    @hits = Service.search do
      keywords params[:q] || ""
    end
  end

  # PUT /services/1/subscribe
  def subscribe
    current_user.subscribe_to params[:id]
    flash[:notice] = "Subscribed!"
    redirect_to services_url
  end

  private
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :site_name %><br />
    <%= f.text_field :site_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :hours %><br />
    <%= f.text_field :hours %>
  </div>
  <div class="field">
    <%= f.label :transportation %><br />
    <%= f.text_field :transportation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/_service.html.erb
<li class="service">
  <span><%= service.site_name %></span>
</li>

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<h1>Listing services</h1>
<ul class="services">
<% @services.each do |service| %>
  <li>
    <h3><%= service.site_name %></h3>
    <div class="actions">
      <%= link_to "View", service_path(service), :class => "button" %>
      <% if current_user.subscribed_to? service %>
        <span class="button">Subscribed!</span>
      <% else %>
        <%= link_to "Subscribe", subscribe_service_path(service), :class => "button", :method => :put %>
      <% end %>
      <%= link_to "Join", "", :class => "button" %>
      <%= link_to "Edit", edit_service_path(service), :class => "button" %>
      <%= link_to 'Destroy', service, :confirm => 'Are you sure?', :method => :delete, :class => "button" %>
    </div>
    <div class="service-types">
      Services Provided:
      <% service.service_types.each do |s| %>
        <span><%= s.title %></span>
      <% end %>
    </div>
    <div class="address">
      <%= service.address %><br/>
      <%= service.city %> <br/>
      <%= service.state %> <br/>
      <%= service.zip %> <br/>
    </div>

<% end %>

<br />

<%= link_to 'New Service', new_service_path, :class => "button" %>

app/views/services/new.html.erb
<h1>New service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/search.html.erb
<ul class="results">
  <% @hits.each_hit_with_result do |hit, service| %>
  <li class="result">
    <div><%= service.site_name %></div>
    <div>Services Provided: <%= service.service_types.map {|s| s.title}.join(", ") %></div>
  </li>
  <% end %>
  <% if @hits.total == 0 %>
    <li class="result empty">
      No Results
    </li>
  <% end %>
</ul>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Site name:</b>
  <%= @service.site_name %>
</p>

<p>
  <b>Address:</b>
  <%= @service.address %>
</p>

<p>
  <b>City:</b>
  <%= @service.city %>
</p>

<p>
  <b>State:</b>
  <%= @service.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @service.zip %>
</p>

<p>
  <b>Phone:</b>
  <%= @service.phone %>
</p>

<p>
  <b>Hours:</b>
  <%= @service.hours %>
</p>

<p>
  <b>Transportation:</b>
  <%= @service.transportation %>
</p>


<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>

<div id="map_canvas" class="google-map" data-lat="-34.397" data-lng="150.644">
</div>