config/routes.rb
BridgeProject::Application.routes.draw do
  devise_for :users

  root :to => "home#index"

  resources :services do
    member do
      put 'subscribe'
    end
  end

  match "search" => "services#search", :as => :search

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BridgeProject</title>
  <link href='http://fonts.googleapis.com/css?family=Amaranth' rel='stylesheet' type='text/css'>
  <%# <link href='/css.htm?family=Amaranth' rel='stylesheet' type='text/css'>%>
  <%= stylesheet_link_tag 'screen.css', :media => 'screen, projection' %>
  <%= stylesheet_link_tag 'print.css', :media => 'print' %>
  <%# /[if IE]%>
  <%# <%= stylesheet_link_tag 'ie.css', :media => 'screen, projection' %>
  <%# <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <script type="text/javascript"
      src="http://maps.google.com/maps/api/js?sensor=false">
    </script>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="main">
    <div id="header">
      <div id="user-bar">
        <ul>

          <% if current_user -%>
            <li><%= current_user.first_name %></li>
          <% else -%>
            <li><%= link_to "Sign In", new_user_session_url %></li>
          <% end -%>

          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Inbox</a></li>
          <li><a href="#">Account</a></li>
          <li><a href="#">Settings</a></li>
          <% if current_user %>
            <li><%= link_to "Log Out", destroy_user_session_url %></li>
          <% end %>
        </ul>
      </div>
      <h1>The BRIDGE Project</h1>
      <h2>DC Social Service Research Guide</h2>
      <div id="nav">
        <ul>
          <li>
            <%= link_to "Home", "/", :unless => :current %>
            <%= link_to "Browse Services", services_path, :unless => :current %>
            <%= link_to "Add Service", new_service_path, :unless => :current %>
            <%= link_to "About BRIDGE", "#", :unless => :current %>
            <%= link_to "Blog", "#", :unless => :current %>
          <li></li>
        </ul>
        <span class="search">
          <%= form_tag search_path, :method => :get do |f| %>
            <input placeholder="Search (ie: Job training)"type="text" name="q" />
            <button>Search</button>
          <% end %>
        </span>
      </div>
    </div>

    <div id="site">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <div id="footer">
      <ul>
        <li><a href="#">Contact Us</a>|</li>
        <li><a href="#">Blog</a>|</li>
        <li><a href="#">About</a>|</li>
        <li><a href="#">Some other text...</a></li>
      </ul>
    </div>
  </div>
</body>
</html>